project:
  output-dir: _output
  render: 
    - "*.qmd"

format:
  math-web-html:
    theme:
      - custom.scss


bibliography: references.bib

number-sections: true

pseudocode:
  caption-number: true

filters:
  - pseudocode
  - thms
